name: notesharing_app
description: A Note Sharing Mobile Application for Students

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  file_picker: ^8.1.6
  path_provider: ^2.1.2
  open_file: ^3.3.0
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  google_fonts: ^6.1.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
